
# Python script to generate Objective-C code for all countries

countries = [
    ("AF", "阿富汗", "Afghanistan", "ps", "AFN", "Asia/Kabul"),
    ("AL", "阿尔巴尼亚", "Albania", "sq", "ALL", "Europe/Tirane"),
    ("DZ", "阿尔及利亚", "Algeria", "ar", "DZD", "Africa/Algiers"),
    ("AS", "美属萨摩亚", "American Samoa", "en", "USD", "Pacific/Pago_Pago"),
    ("AD", "安道尔", "Andorra", "ca", "EUR", "Europe/Andorra"),
    ("AO", "安哥拉", "Angola", "pt", "AOA", "Africa/Luanda"),
    ("AI", "安圭拉", "Anguilla", "en", "XCD", "America/Anguilla"),
    ("AQ", "南极洲", "Antarctica", "en", "AQD", "Antarctica/McMurdo"), # Placeholder currency/tz
    ("AG", "安提瓜和巴布达", "Antigua and Barbuda", "en", "XCD", "America/Antigua"),
    ("AR", "阿根廷", "Argentina", "es", "ARS", "America/Argentina/Buenos_Aires"),
    ("AM", "亚美尼亚", "Armenia", "hy", "AMD", "Asia/Yerevan"),
    ("AW", "阿鲁巴", "Aruba", "nl", "AWG", "America/Aruba"),
    ("AU", "澳大利亚", "Australia", "en", "AUD", "Australia/Sydney"),
    ("AT", "奥地利", "Austria", "de", "EUR", "Europe/Vienna"),
    ("AZ", "阿塞拜疆", "Azerbaijan", "az", "AZN", "Asia/Baku"),
    ("BS", "巴哈马", "Bahamas", "en", "BSD", "America/Nassau"),
    ("BH", "巴林", "Bahrain", "ar", "BHD", "Asia/Bahrain"),
    ("BD", "孟加拉国", "Bangladesh", "bn", "BDT", "Asia/Dhaka"),
    ("BB", "巴巴多斯", "Barbados", "en", "BBD", "America/Barbados"),
    ("BY", "白俄罗斯", "Belarus", "be", "BYN", "Europe/Minsk"),
    ("BE", "比利时", "Belgium", "fr", "EUR", "Europe/Brussels"),
    ("BZ", "伯利兹", "Belize", "en", "BZD", "America/Belize"),
    ("BJ", "贝宁", "Benin", "fr", "XOF", "Africa/Porto-Novo"),
    ("BM", "百慕大", "Bermuda", "en", "BMD", "Atlantic/Bermuda"),
    ("BT", "不丹", "Bhutan", "dz", "BTN", "Asia/Thimphu"),
    ("BO", "玻利维亚", "Bolivia", "es", "BOB", "America/La_Paz"),
    ("BA", "波黑", "Bosnia and Herzegovina", "bs", "BAM", "Europe/Sarajevo"),
    ("BW", "博茨瓦纳", "Botswana", "en", "BWP", "Africa/Gaborone"),
    ("BV", "布维岛", "Bouvet Island", "nb", "NOK", "Europe/Oslo"),
    ("BR", "巴西", "Brazil", "pt", "BRL", "America/Sao_Paulo"),
    ("IO", "英属印度洋领地", "British Indian Ocean Territory", "en", "USD", "Indian/Chagos"),
    ("BN", "文莱", "Brunei Darussalam", "ms", "BND", "Asia/Brunei"),
    ("BG", "保加利亚", "Bulgaria", "bg", "BGN", "Europe/Sofia"),
    ("BF", "布基纳法索", "Burkina Faso", "fr", "XOF", "Africa/Ouagadougou"),
    ("BI", "布隆迪", "Burundi", "fr", "BIF", "Africa/Bujumbura"),
    ("KH", "柬埔寨", "Cambodia", "km", "KHR", "Asia/Phnom_Penh"),
    ("CM", "喀麦隆", "Cameroon", "en", "XAF", "Africa/Douala"),
    ("CA", "加拿大", "Canada", "en", "CAD", "America/Toronto"),
    ("CV", "佛得角", "Cape Verde", "pt", "CVE", "Atlantic/Cape_Verde"),
    ("KY", "开曼群岛", "Cayman Islands", "en", "KYD", "America/Cayman"),
    ("CF", "中非", "Central African Republic", "fr", "XAF", "Africa/Bangui"),
    ("TD", "乍得", "Chad", "fr", "XAF", "Africa/Ndjamena"),
    ("CL", "智利", "Chile", "es", "CLP", "America/Santiago"),
    ("CN", "中国", "China", "zh-Hans", "CNY", "Asia/Shanghai"),
    ("CX", "圣诞岛", "Christmas Island", "en", "AUD", "Indian/Christmas"),
    ("CC", "科科斯（基林）群岛", "Cocos (Keeling) Islands", "en", "AUD", "Indian/Cocos"),
    ("CO", "哥伦比亚", "Colombia", "es", "COP", "America/Bogota"),
    ("KM", "科摩罗", "Comoros", "fr", "KMF", "Indian/Comoro"),
    ("CG", "刚果（布）", "Congo", "fr", "XAF", "Africa/Brazzaville"),
    ("CD", "刚果（金）", "Congo, The Democratic Republic of the", "fr", "CDF", "Africa/Kinshasa"),
    ("CK", "库克群岛", "Cook Islands", "en", "NZD", "Pacific/Rarotonga"),
    ("CR", "哥斯达黎加", "Costa Rica", "es", "CRC", "America/Costa_Rica"),
    ("CI", "科特迪瓦", "Cote D'Ivoire", "fr", "XOF", "Africa/Abidjan"),
    ("HR", "克罗地亚", "Croatia", "hr", "HRK", "Europe/Zagreb"),
    ("CU", "古巴", "Cuba", "es", "CUP", "America/Havana"),
    ("CY", "塞浦路斯", "Cyprus", "el", "EUR", "Asia/Nicosia"),
    ("CZ", "捷克", "Czech Republic", "cs", "CZK", "Europe/Prague"),
    ("DK", "丹麦", "Denmark", "da", "DKK", "Europe/Copenhagen"),
    ("DJ", "吉布提", "Djibouti", "fr", "DJF", "Africa/Djibouti"),
    ("DM", "多米尼克", "Dominica", "en", "XCD", "America/Dominica"),
    ("DO", "多米尼加共和国", "Dominican Republic", "es", "DOP", "America/Santo_Domingo"),
    ("EC", "厄瓜多尔", "Ecuador", "es", "USD", "America/Guayaquil"),
    ("EG", "埃及", "Egypt", "ar", "EGP", "Africa/Cairo"),
    ("SV", "萨尔瓦多", "El Salvador", "es", "USD", "America/El_Salvador"),
    ("GQ", "赤道几内亚", "Equatorial Guinea", "es", "XAF", "Africa/Malabo"),
    ("ER", "厄立特里亚", "Eritrea", "ti", "ERN", "Africa/Asmara"),
    ("EE", "爱沙尼亚", "Estonia", "et", "EUR", "Europe/Tallinn"),
    ("ET", "埃塞俄比亚", "Ethiopia", "am", "ETB", "Africa/Addis_Ababa"),
    ("FK", "福克兰群岛", "Falkland Islands (Malvinas)", "en", "FKP", "Atlantic/Stanley"),
    ("FO", "法罗群岛", "Faroe Islands", "fo", "DKK", "Atlantic/Faroe"),
    ("FJ", "斐济", "Fiji", "en", "FJD", "Pacific/Fiji"),
    ("FI", "芬兰", "Finland", "fi", "EUR", "Europe/Helsinki"),
    ("FR", "法国", "France", "fr", "EUR", "Europe/Paris"),
    ("GF", "法属圭亚那", "French Guiana", "fr", "EUR", "America/Cayenne"),
    ("PF", "法属波利尼西亚", "French Polynesia", "fr", "XPF", "Pacific/Tahiti"),
    ("TF", "法属南部领地", "French Southern Territories", "fr", "EUR", "Indian/Kerguelen"), # Est
    ("GA", "加蓬", "Gabon", "fr", "XAF", "Africa/Libreville"),
    ("GM", "冈比亚", "Gambia", "en", "GMD", "Africa/Banjul"),
    ("GE", "格鲁吉亚", "Georgia", "ka", "GEL", "Asia/Tbilisi"),
    ("DE", "德国", "Germany", "de", "EUR", "Europe/Berlin"),
    ("GH", "加纳", "Ghana", "en", "GHS", "Africa/Accra"),
    ("GI", "直布罗陀", "Gibraltar", "en", "GIP", "Europe/Gibraltar"),
    ("GR", "希腊", "Greece", "el", "EUR", "Europe/Athens"),
    ("GL", "格陵兰", "Greenland", "kl", "DKK", "America/Godthab"),
    ("GD", "格林纳达", "Grenada", "en", "XCD", "America/Grenada"),
    ("GP", "瓜德罗普", "Guadeloupe", "fr", "EUR", "America/Guadeloupe"),
    ("GU", "关岛", "Guam", "en", "USD", "Pacific/Guam"),
    ("GT", "危地马拉", "Guatemala", "es", "GTQ", "America/Guatemala"),
    ("GG", "根西", "Guernsey", "en", "GBP", "Europe/Guernsey"),
    ("GN", "几内亚", "Guinea", "fr", "GNF", "Africa/Conakry"),
    ("GW", "几内亚比绍", "Guinea-Bissau", "pt", "XOF", "Africa/Bissau"),
    ("GY", "圭亚那", "Guyana", "en", "GYD", "America/Guyana"),
    ("HT", "海地", "Haiti", "fr", "HTG", "America/Port-au-Prince"),
    ("HM", "赫德岛和麦克唐纳群岛", "Heard Island and McDonald Islands", "en", "AUD", "Indian/Maldives"), # Placeholder
    ("VA", "梵蒂冈", "Holy See (Vatican City State)", "it", "EUR", "Europe/Vatican"),
    ("HN", "洪都拉斯", "Honduras", "es", "HNL", "America/Tegucigalpa"),
    ("HK", "中国香港", "Hong Kong", "zh-Hant", "HKD", "Asia/Hong_Kong"),
    ("HU", "匈牙利", "Hungary", "hu", "HUF", "Europe/Budapest"),
    ("IS", "冰岛", "Iceland", "is", "ISK", "Atlantic/Reykjavik"),
    ("IN", "印度", "India", "en", "INR", "Asia/Kolkata"),
    ("ID", "印度尼西亚", "Indonesia", "id", "IDR", "Asia/Jakarta"),
    ("IR", "伊朗", "Iran, Islamic Republic of", "fa", "IRR", "Asia/Tehran"),
    ("IQ", "伊拉克", "Iraq", "ar", "IQD", "Asia/Baghdad"),
    ("IE", "爱尔兰", "Ireland", "ga", "EUR", "Europe/Dublin"),
    ("IM", "马恩岛", "Isle of Man", "en", "GBP", "Europe/Isle_of_Man"),
    ("IL", "以色列", "Israel", "he", "ILS", "Asia/Jerusalem"),
    ("IT", "意大利", "Italy", "it", "EUR", "Europe/Rome"),
    ("JM", "牙买加", "Jamaica", "en", "JMD", "America/Jamaica"),
    ("JP", "日本", "Japan", "ja", "JPY", "Asia/Tokyo"),
    ("JE", "泽西", "Jersey", "en", "GBP", "Europe/Jersey"),
    ("JO", "约旦", "Jordan", "ar", "JOD", "Asia/Amman"),
    ("KZ", "哈萨克斯坦", "Kazakhstan", "kk", "KZT", "Asia/Almaty"),
    ("KE", "肯尼亚", "Kenya", "sw", "KES", "Africa/Nairobi"),
    ("KI", "基里巴斯", "Kiribati", "en", "AUD", "Pacific/Tarawa"),
    ("KP", "朝鲜", "Korea, Democratic People's Republic of", "ko", "KPW", "Asia/Pyongyang"),
    ("KR", "韩国", "South Korea", "ko", "KRW", "Asia/Seoul"),
    ("KW", "科威特", "Kuwait", "ar", "KWD", "Asia/Kuwait"),
    ("KG", "吉尔吉斯斯坦", "Kyrgyzstan", "ky", "KGS", "Asia/Bishkek"),
    ("LA", "老挝", "Lao People's Democratic Republic", "lo", "LAK", "Asia/Vientiane"),
    ("LV", "拉脱维亚", "Latvia", "lv", "EUR", "Europe/Riga"),
    ("LB", "黎巴嫩", "Lebanon", "ar", "LBP", "Asia/Beirut"),
    ("LS", "莱索托", "Lesotho", "st", "LSL", "Africa/Maseru"),
    ("LR", "利比里亚", "Liberia", "en", "LRD", "Africa/Monrovia"),
    ("LY", "利比亚", "Libyan Arab Jamahiriya", "ar", "LYD", "Africa/Tripoli"),
    ("LI", "列支敦士登", "Liechtenstein", "de", "CHF", "Europe/Vaduz"),
    ("LT", "立陶宛", "Lithuania", "lt", "EUR", "Europe/Vilnius"),
    ("LU", "卢森堡", "Luxembourg", "fr", "EUR", "Europe/Luxembourg"),
    ("MO", "中国澳门", "Macao", "zh-Hant", "MOP", "Asia/Macau"),
    ("MK", "北马其顿", "Macedonia, The Former Yugoslav Republic of", "mk", "MKD", "Europe/Skopje"),
    ("MG", "马达加斯加", "Madagascar", "fr", "MGA", "Indian/Antananarivo"),
    ("MW", "马拉维", "Malawi", "en", "MWK", "Africa/Blantyre"),
    ("MY", "马来西亚", "Malaysia", "ms", "MYR", "Asia/Kuala_Lumpur"),
    ("MV", "马尔代夫", "Maldives", "dv", "MVR", "Indian/Maldives"),
    ("ML", "马里", "Mali", "fr", "XOF", "Africa/Bamako"),
    ("MT", "马耳他", "Malta", "mt", "EUR", "Europe/Malta"),
    ("MH", "马绍尔群岛", "Marshall Islands", "en", "USD", "Pacific/Majuro"),
    ("MQ", "马提尼克", "Martinique", "fr", "EUR", "America/Martinique"),
    ("MR", "毛里塔尼亚", "Mauritania", "ar", "MRU", "Africa/Nouakchott"),
    ("MU", "毛里求斯", "Mauritius", "en", "MUR", "Indian/Mauritius"),
    ("YT", "马约特", "Mayotte", "fr", "EUR", "Indian/Mayotte"),
    ("MX", "墨西哥", "Mexico", "es", "MXN", "America/Mexico_City"),
    ("FM", "密克罗尼西亚", "Micronesia, Federated States of", "en", "USD", "Pacific/Pohnpei"),
    ("MD", "摩尔多瓦", "Moldova, Republic of", "ro", "MDL", "Europe/Chisinau"),
    ("MC", "摩纳哥", "Monaco", "fr", "EUR", "Europe/Monaco"),
    ("MN", "蒙古", "Mongolia", "mn", "MNT", "Asia/Ulaanbaatar"),
    ("ME", "黑山", "Montenegro", "sr", "EUR", "Europe/Podgorica"),
    ("MS", "蒙特塞拉特", "Montserrat", "en", "XCD", "America/Montserrat"),
    ("MA", "摩洛哥", "Morocco", "ar", "MAD", "Africa/Casablanca"),
    ("MZ", "莫桑比克", "Mozambique", "pt", "MZN", "Africa/Maputo"),
    ("MM", "缅甸", "Myanmar", "my", "MMK", "Asia/Yangon"),
    ("NA", "纳米比亚", "Namibia", "en", "NAD", "Africa/Windhoek"),
    ("NR", "瑙鲁", "Nauru", "en", "AUD", "Pacific/Nauru"),
    ("NP", "尼泊尔", "Nepal", "ne", "NPR", "Asia/Kathmandu"),
    ("NL", "荷兰", "Netherlands", "nl", "EUR", "Europe/Amsterdam"),
    ("NC", "新喀里多尼亚", "New Caledonia", "fr", "XPF", "Pacific/Noumea"),
    ("NZ", "新西兰", "New Zealand", "en", "NZD", "Pacific/Auckland"),
    ("NI", "尼加拉瓜", "Nicaragua", "es", "NIO", "America/Managua"),
    ("NE", "尼日尔", "Niger", "fr", "XOF", "Africa/Niamey"),
    ("NG", "尼日利亚", "Nigeria", "en", "NGN", "Africa/Lagos"),
    ("NU", "纽埃", "Niue", "en", "NZD", "Pacific/Niue"),
    ("NF", "诺福克岛", "Norfolk Island", "en", "AUD", "Pacific/Norfolk"),
    ("MP", "北马里亚纳群岛", "Northern Mariana Islands", "en", "USD", "Pacific/Saipan"),
    ("NO", "挪威", "Norway", "nb", "NOK", "Europe/Oslo"),
    ("OM", "阿曼", "Oman", "ar", "OMR", "Asia/Muscat"),
    ("PK", "巴基斯坦", "Pakistan", "ur", "PKR", "Asia/Karachi"),
    ("PW", "帕劳", "Palau", "en", "USD", "Pacific/Palau"),
    ("PS", "巴勒斯坦", "Palestinian Territory, Occupied", "ar", "ILS", "Asia/Gaza"),
    ("PA", "巴拿马", "Panama", "es", "PAB", "America/Panama"),
    ("PG", "巴布亚新几内亚", "Papua New Guinea", "en", "PGK", "Pacific/Port_Moresby"),
    ("PY", "巴拉圭", "Paraguay", "es", "PYG", "America/Asuncion"),
    ("PE", "秘鲁", "Peru", "es", "PEN", "America/Lima"),
    ("PH", "菲律宾", "Philippines", "en", "PHP", "Asia/Manila"),
    ("PN", "皮特凯恩", "Pitcairn", "en", "NZD", "Pacific/Pitcairn"),
    ("PL", "波兰", "Poland", "pl", "PLN", "Europe/Warsaw"),
    ("PT", "葡萄牙", "Portugal", "pt", "EUR", "Europe/Lisbon"),
    ("PR", "波多黎各", "Puerto Rico", "es", "USD", "America/Puerto_Rico"),
    ("QA", "卡塔尔", "Qatar", "ar", "QAR", "Asia/Qatar"),
    ("RE", "留尼汪", "Reunion", "fr", "EUR", "Indian/Reunion"),
    ("RO", "罗马尼亚", "Romania", "ro", "RON", "Europe/Bucharest"),
    ("RU", "俄罗斯", "Russian Federation", "ru", "RUB", "Europe/Moscow"),
    ("RW", "卢旺达", "Rwanda", "rw", "RWF", "Africa/Kigali"),
    ("SH", "圣赫勒拿", "Saint Helena", "en", "SHP", "Atlantic/St_Helena"),
    ("KN", "圣基茨和尼维斯", "Saint Kitts and Nevis", "en", "XCD", "America/St_Kitts"),
    ("LC", "圣卢西亚", "Saint Lucia", "en", "XCD", "America/St_Lucia"),
    ("PM", "圣皮埃尔和密克隆", "Saint Pierre and Miquelon", "fr", "EUR", "America/Miquelon"),
    ("VC", "圣文森特和格林纳丁斯", "Saint Vincent and the Grenadines", "en", "XCD", "America/St_Vincent"),
    ("WS", "萨摩亚", "Samoa", "sm", "WST", "Pacific/Apia"),
    ("SM", "圣马力诺", "San Marino", "it", "EUR", "Europe/San_Marino"),
    ("ST", "圣多美和普林西比", "Sao Tome and Principe", "pt", "STN", "Africa/Sao_Tome"),
    ("SA", "沙特阿拉伯", "Saudi Arabia", "ar", "SAR", "Asia/Riyadh"),
    ("SN", "塞内加尔", "Senegal", "fr", "XOF", "Africa/Dakar"),
    ("RS", "塞尔维亚", "Serbia", "sr", "RSD", "Europe/Belgrade"),
    ("SC", "塞舌尔", "Seychelles", "en", "SCR", "Indian/Mahe"),
    ("SL", "塞拉利昂", "Sierra Leone", "en", "SLL", "Africa/Freetown"),
    ("SG", "新加坡", "Singapore", "en", "SGD", "Asia/Singapore"),
    ("SK", "斯洛伐克", "Slovakia", "sk", "EUR", "Europe/Bratislava"),
    ("SI", "斯洛文尼亚", "Slovenia", "sl", "EUR", "Europe/Ljubljana"),
    ("SB", "所罗门群岛", "Solomon Islands", "en", "SBD", "Pacific/Guadalcanal"),
    ("SO", "索马里", "Somalia", "so", "SOS", "Africa/Mogadishu"),
    ("ZA", "南非", "South Africa", "en", "ZAR", "Africa/Johannesburg"),
    ("ES", "西班牙", "Spain", "es", "EUR", "Europe/Madrid"),
    ("LK", "斯里兰卡", "Sri Lanka", "si", "LKR", "Asia/Colombo"),
    ("SD", "苏丹", "Sudan", "ar", "SDG", "Africa/Khartoum"),
    ("SR", "苏里南", "Suriname", "nl", "SRD", "America/Paramaribo"),
    ("SJ", "斯瓦尔巴和扬马延", "Svalbard and Jan Mayen", "no", "NOK", "Arctic/Longyearbyen"),
    ("SZ", "斯威士兰", "Swaziland", "en", "SZL", "Africa/Mbabane"),
    ("SE", "瑞典", "Sweden", "sv", "SEK", "Europe/Stockholm"),
    ("CH", "瑞士", "Switzerland", "de", "CHF", "Europe/Zurich"),
    ("SY", "叙利亚", "Syrian Arab Republic", "ar", "SYP", "Asia/Damascus"),
    ("TW", "中国台湾", "Taiwan", "zh-Hant", "TWD", "Asia/Taipei"),
    ("TJ", "塔吉克斯坦", "Tajikistan", "tg", "TJS", "Asia/Dushanbe"),
    ("TZ", "坦桑尼亚", "Tanzania, United Republic of", "sw", "TZS", "Africa/Dar_es_Salaam"),
    ("TH", "泰国", "Thailand", "th", "THB", "Asia/Bangkok"),
    ("TL", "东帝汶", "Timor-Leste", "pt", "USD", "Asia/Dili"),
    ("TG", "多哥", "Togo", "fr", "XOF", "Africa/Lome"),
    ("TK", "托克劳", "Tokelau", "en", "NZD", "Pacific/Fakaofo"),
    ("TO", "汤加", "Tonga", "to", "TOP", "Pacific/Tongatapu"),
    ("TT", "特立尼达和多巴哥", "Trinidad and Tobago", "en", "TTD", "America/Port_of_Spain"),
    ("TN", "突尼斯", "Tunisia", "ar", "TND", "Africa/Tunis"),
    ("TR", "土耳其", "Turkey", "tr", "TRY", "Europe/Istanbul"),
    ("TM", "土库曼斯坦", "Turkmenistan", "tk", "TMT", "Asia/Ashgabat"),
    ("TC", "特克斯和凯科斯群岛", "Turks and Caicos Islands", "en", "USD", "America/Grand_Turk"),
    ("TV", "图瓦卢", "Tuvalu", "en", "AUD", "Pacific/Funafuti"),
    ("UG", "乌干达", "Uganda", "en", "UGX", "Africa/Kampala"),
    ("UA", "乌克兰", "Ukraine", "uk", "UAH", "Europe/Kiev"),
    ("AE", "阿联酋", "United Arab Emirates", "ar", "AED", "Asia/Dubai"),
    ("GB", "英国", "United Kingdom", "en", "GBP", "Europe/London"),
    ("US", "美国", "United States", "en", "USD", "America/New_York"),
    ("UY", "乌拉圭", "Uruguay", "es", "UYU", "America/Montevideo"),
    ("UZ", "乌兹别克斯坦", "Uzbekistan", "uz", "UZS", "Asia/Tashkent"),
    ("VU", "瓦努阿图", "Vanuatu", "en", "VUV", "Pacific/Efate"),
    ("VE", "委内瑞拉", "Venezuela", "es", "VES", "America/Caracas"),
    ("VN", "越南", "Vietnam", "vi", "VND", "Asia/Ho_Chi_Minh"),
    ("VG", "英属维尔京群岛", "Virgin Islands, British", "en", "USD", "America/Tortola"),
    ("VI", "美属维尔京群岛", "Virgin Islands, U.S.", "en", "USD", "America/St_Thomas"),
    ("WF", "瓦利斯和富图纳", "Wallis and Futuna", "fr", "XPF", "Pacific/Wallis"),
    ("EH", "西撒哈拉", "Western Sahara", "ar", "MAD", "Africa/El_Aaiun"),
    ("YE", "也门", "Yemen", "ar", "YER", "Asia/Aden"),
    ("ZM", "赞比亚", "Zambia", "en", "ZMW", "Africa/Lusaka"),
    ("ZW", "津巴布韦", "Zimbabwe", "en", "ZWL", "Africa/Harare"),
]

for c in countries:
    code, cn, en, lang, curr, tz = c
    print(f'    add(@"{code}", @"{cn}", @"{en}", @"{lang}", @"{curr}", @"{tz}");')
